---
- name: "Download Filebeat's rpm"
  when: ansible_connection != "community.docker.docker"
  include: rpm.yml

- name: Install Filebeat tar.gz (on Docker)
  when: ansible_connection == "community.docker.docker"
  include: targz.yml
